#!/usr/bin/env python3
"""Serve the polish mode's priority lane: the next entries from
polishing/priority/notes.txt that nobody has polished in the last 30 days.

    python3 pipeline/priority_lane.py next --n 15     # JSON: ids, regenerated (writes nothing else)
    python3 pipeline/priority_lane.py record --priority 02871,03423 --frontier 08599,08600

`next` starts at the line in polishing/tasks/comprehensive/priority-cursor.txt
and skips IDs with no entry file and IDs in the polished ledger
(polishing/tasks/comprehensive/polished.jsonl) within SKIP_DAYS. It does not
write anything unless the list is exhausted or older than REGEN_DAYS: then it
regenerates the list (build/prioritize_polishing.py) and starts again at line 1.

`record` appends every ID a polish cycle read (both lanes) to the ledger and
moves the priority cursor to the line after the last --priority ID it finds at
or after the cursor, so IDs served but not read are served again next time.

Why a ledger: the lane used to skip entries whose metadata.modified was in the
last 30 days, but the mechanical passes (links, cross-references, tags,
has_audio) touch nearly every entry, so in September 2026 27,542 of the 27,549
listed entries were "recent" and the cursor ran to the end without serving any.
"""
import argparse
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTES = ROOT / "polishing" / "priority" / "notes.txt"
CURSOR = ROOT / "polishing" / "tasks" / "comprehensive" / "priority-cursor.txt"
LEDGER = ROOT / "polishing" / "tasks" / "comprehensive" / "polished.jsonl"
SKIP_DAYS = 30
REGEN_DAYS = 14


def today():
    return dt.datetime.now(dt.timezone.utc).date()


def read_cursor(path=CURSOR):
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("line:"):
                return max(1, int(line.split(":", 1)[1]))
    except (OSError, ValueError):
        pass
    return 1


def write_cursor(n, path=CURSOR):
    path.write_text(f"line: {n}\n", encoding="utf-8")


def recently_polished(ledger=LEDGER, days=SKIP_DAYS, on=None):
    cutoff = ((on or today()) - dt.timedelta(days=days)).isoformat()
    ids = set()
    if ledger.exists():
        for line in ledger.read_text(encoding="utf-8").splitlines():
            if line.strip():
                r = json.loads(line)
                if r.get("date", "") >= cutoff:
                    ids.add(r["id"])
    return ids


def list_date(lines):
    """The 'Generated by … on YYYY-MM-DD' header date, or None."""
    for line in lines[:5]:
        if line.startswith("# Generated") and " on " in line:
            try:
                return dt.date.fromisoformat(line.rsplit(" on ", 1)[1].strip()[:10])
            except ValueError:
                return None
    return None


def entry_ids():
    return {p.name.split("_", 1)[0] for p in (ROOT / "entries").glob("*/*.json")}


def pick(lines, start, n, skip, exists):
    """From 1-based line `start`, return (ids, cursor_after). Header lines
    (#) and blank lines are passed over. `ids` are 'NNNNN_romaji' keys."""
    ids, i = [], start - 1
    while i < len(lines) and len(ids) < n:
        key = lines[i].strip()
        i += 1
        if not key or key.startswith("#"):
            continue
        num = key.split("_", 1)[0]
        if num in skip or num not in exists:
            continue
        ids.append(key)
    return ids, i + 1


def cmd_next(args):
    lines = NOTES.read_text(encoding="utf-8").splitlines() if NOTES.exists() else []
    skip = recently_polished()
    exists = entry_ids()
    start = read_cursor()
    made = list_date(lines)
    regenerated = False
    ids, after = pick(lines, start, args.n, skip, exists)
    stale = made is None or (today() - made).days > REGEN_DAYS
    if not ids or stale:
        subprocess.run([sys.executable, str(ROOT / "build" / "prioritize_polishing.py")],
                       cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
        write_cursor(1)
        lines = NOTES.read_text(encoding="utf-8").splitlines()
        ids, after = pick(lines, 1, args.n, skip, exists)
        regenerated = True
    print(json.dumps({"ids": ids, "regenerated": regenerated,
                      "list_generated": str(list_date(lines)), "skipped_recent": len(skip)},
                     ensure_ascii=False, indent=2))
    return 0


def split_ids(text):
    return [x.strip().split("_", 1)[0] for x in (text or "").split(",") if x.strip()]


def advance(lines, start, read):
    """Line after the last line at or after `start` whose ID is in `read`;
    `start` if none is."""
    after = start
    for i in range(start - 1, len(lines)):
        if lines[i].strip().split("_", 1)[0] in read:
            after = i + 2
    return after


def cmd_record(args):
    prio, front = split_ids(args.priority), split_ids(args.frontier)
    d = today().isoformat()
    ids = list(dict.fromkeys(prio + front))
    with open(LEDGER, "a", encoding="utf-8") as f:
        for i in ids:
            f.write(json.dumps({"date": d, "id": i}) + "\n")
    msg = f"recorded {len(ids)} polished IDs"
    if prio:
        lines = NOTES.read_text(encoding="utf-8").splitlines()
        start = read_cursor()
        after = advance(lines, start, set(prio))
        write_cursor(after)
        msg += f"; priority cursor line {start} → {after}"
    print(msg)
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("next")
    p.add_argument("--n", type=int, default=15)
    p = sub.add_parser("record")
    p.add_argument("--priority", default="", help="priority-lane IDs read (NNNNN or NNNNN_romaji, comma-separated)")
    p.add_argument("--frontier", default="", help="frontier-lane IDs read")
    args = ap.parse_args(argv)
    return {"next": cmd_next, "record": cmd_record}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
